import { registerLanguage } from "react-refractor";

import abap from "refractor/lang/abap";
import abnf from "refractor/lang/abnf";
import actionscript from "refractor/lang/actionscript";
import ada from "refractor/lang/ada";
import agda from "refractor/lang/agda";
import al from "refractor/lang/al";
import antlr4 from "refractor/lang/antlr4";
import apacheconf from "refractor/lang/apacheconf";
import apex from "refractor/lang/apex";
import apl from "refractor/lang/apl";
import applescript from "refractor/lang/applescript";
import aql from "refractor/lang/aql";
import arduino from "refractor/lang/arduino";
import arff from "refractor/lang/arff";
import armasm from "refractor/lang/armasm";
import arturo from "refractor/lang/arturo";
import asciidoc from "refractor/lang/asciidoc";
import aspnet from "refractor/lang/aspnet";
import asm6502 from "refractor/lang/asm6502";
import asmatmel from "refractor/lang/asmatmel";
import autohotkey from "refractor/lang/autohotkey";
import autoit from "refractor/lang/autoit";
import avisynth from "refractor/lang/avisynth";
import avro_idl from "refractor/lang/avro-idl";
import awk from "refractor/lang/awk";
import bash from "refractor/lang/bash";
import basic from "refractor/lang/basic";
import batch from "refractor/lang/batch";
import bbcode from "refractor/lang/bbcode";
import bbj from "refractor/lang/bbj";
import bicep from "refractor/lang/bicep";
import birb from "refractor/lang/birb";
import bison from "refractor/lang/bison";
import bnf from "refractor/lang/bnf";
import bqn from "refractor/lang/bqn";
import brainfuck from "refractor/lang/brainfuck";
import brightscript from "refractor/lang/brightscript";
import bro from "refractor/lang/bro";
import bsl from "refractor/lang/bsl";
import c from "refractor/lang/c";
import csharp from "refractor/lang/csharp";
import cpp from "refractor/lang/cpp";
import cfscript from "refractor/lang/cfscript";
import chaiscript from "refractor/lang/chaiscript";
import cil from "refractor/lang/cil";
import cilkc from "refractor/lang/cilkc";
import cilkcpp from "refractor/lang/cilkcpp";
import clojure from "refractor/lang/clojure";
import cmake from "refractor/lang/cmake";
import cobol from "refractor/lang/cobol";
import coffeescript from "refractor/lang/coffeescript";
import concurnas from "refractor/lang/concurnas";
import csp from "refractor/lang/csp";
import cooklang from "refractor/lang/cooklang";
import coq from "refractor/lang/coq";
import crystal from "refractor/lang/crystal";
import css_extras from "refractor/lang/css-extras";
import csv from "refractor/lang/csv";
import cue from "refractor/lang/cue";
import cypher from "refractor/lang/cypher";
import d from "refractor/lang/d";
import dart from "refractor/lang/dart";
import dataweave from "refractor/lang/dataweave";
import dax from "refractor/lang/dax";
import dhall from "refractor/lang/dhall";
import diff from "refractor/lang/diff";
import django from "refractor/lang/django";
import dns_zone_file from "refractor/lang/dns-zone-file";
import docker from "refractor/lang/docker";
import dot from "refractor/lang/dot";
import ebnf from "refractor/lang/ebnf";
import editorconfig from "refractor/lang/editorconfig";
import eiffel from "refractor/lang/eiffel";
import ejs from "refractor/lang/ejs";
import elixir from "refractor/lang/elixir";
import elm from "refractor/lang/elm";
import etlua from "refractor/lang/etlua";
import erb from "refractor/lang/erb";
import erlang from "refractor/lang/erlang";
import excel_formula from "refractor/lang/excel-formula";
import fsharp from "refractor/lang/fsharp";
import factor from "refractor/lang/factor";
import false_lang from "refractor/lang/false";
import firestore_security_rules from "refractor/lang/firestore-security-rules";
import flow from "refractor/lang/flow";
import fortran from "refractor/lang/fortran";
import ftl from "refractor/lang/ftl";
import gml from "refractor/lang/gml";
import gap from "refractor/lang/gap";
import gcode from "refractor/lang/gcode";
import gdscript from "refractor/lang/gdscript";
import gedcom from "refractor/lang/gedcom";
import gettext from "refractor/lang/gettext";
import gherkin from "refractor/lang/gherkin";
import git from "refractor/lang/git";
import glsl from "refractor/lang/glsl";
import gn from "refractor/lang/gn";
import linker_script from "refractor/lang/linker-script";
import go from "refractor/lang/go";
import go_module from "refractor/lang/go-module";
import gradle from "refractor/lang/gradle";
import graphql from "refractor/lang/graphql";
import groovy from "refractor/lang/groovy";
import haml from "refractor/lang/haml";
import handlebars from "refractor/lang/handlebars";
import haskell from "refractor/lang/haskell";
import haxe from "refractor/lang/haxe";
import hcl from "refractor/lang/hcl";
import hlsl from "refractor/lang/hlsl";
import hoon from "refractor/lang/hoon";
import http from "refractor/lang/http";
import hpkp from "refractor/lang/hpkp";
import hsts from "refractor/lang/hsts";
import ichigojam from "refractor/lang/ichigojam";
import icon from "refractor/lang/icon";
import icu_message_format from "refractor/lang/icu-message-format";
import idris from "refractor/lang/idris";
import ignore from "refractor/lang/ignore";
import inform7 from "refractor/lang/inform7";
import ini from "refractor/lang/ini";
import io from "refractor/lang/io";
import j from "refractor/lang/j";
import java from "refractor/lang/java";
import javadoc from "refractor/lang/javadoc";
import javadoclike from "refractor/lang/javadoclike";
import javastacktrace from "refractor/lang/javastacktrace";
import jexl from "refractor/lang/jexl";
import jolie from "refractor/lang/jolie";
import jq from "refractor/lang/jq";
import jsdoc from "refractor/lang/jsdoc";
import js_extras from "refractor/lang/js-extras";
import json from "refractor/lang/json";
import json5 from "refractor/lang/json5";
import jsonp from "refractor/lang/jsonp";
import jsstacktrace from "refractor/lang/jsstacktrace";
import js_templates from "refractor/lang/js-templates";
import julia from "refractor/lang/julia";
import keepalived from "refractor/lang/keepalived";
import keyman from "refractor/lang/keyman";
import kotlin from "refractor/lang/kotlin";
import kumir from "refractor/lang/kumir";
import kusto from "refractor/lang/kusto";
import latex from "refractor/lang/latex";
import latte from "refractor/lang/latte";
import less from "refractor/lang/less";
import lilypond from "refractor/lang/lilypond";
import liquid from "refractor/lang/liquid";
import lisp from "refractor/lang/lisp";
import livescript from "refractor/lang/livescript";
import llvm from "refractor/lang/llvm";
import log from "refractor/lang/log";
import lolcode from "refractor/lang/lolcode";
import lua from "refractor/lang/lua";
import magma from "refractor/lang/magma";
import makefile from "refractor/lang/makefile";
import markdown from "refractor/lang/markdown";
import markup_templating from "refractor/lang/markup-templating";
import mata from "refractor/lang/mata";
import matlab from "refractor/lang/matlab";
import maxscript from "refractor/lang/maxscript";
import mel from "refractor/lang/mel";
import mermaid from "refractor/lang/mermaid";
import metafont from "refractor/lang/metafont";
import mizar from "refractor/lang/mizar";
import mongodb from "refractor/lang/mongodb";
import monkey from "refractor/lang/monkey";
import moonscript from "refractor/lang/moonscript";
import n1ql from "refractor/lang/n1ql";
import n4js from "refractor/lang/n4js";
import nand2tetris_hdl from "refractor/lang/nand2tetris-hdl";
import naniscript from "refractor/lang/naniscript";
import nasm from "refractor/lang/nasm";
import neon from "refractor/lang/neon";
import nevod from "refractor/lang/nevod";
import nginx from "refractor/lang/nginx";
import nim from "refractor/lang/nim";
import nix from "refractor/lang/nix";
import nsis from "refractor/lang/nsis";
import objectivec from "refractor/lang/objectivec";
import ocaml from "refractor/lang/ocaml";
import odin from "refractor/lang/odin";
import opencl from "refractor/lang/opencl";
import openqasm from "refractor/lang/openqasm";
import oz from "refractor/lang/oz";
import parigp from "refractor/lang/parigp";
import parser from "refractor/lang/parser";
import pascal from "refractor/lang/pascal";
import pascaligo from "refractor/lang/pascaligo";
import psl from "refractor/lang/psl";
import pcaxis from "refractor/lang/pcaxis";
import peoplecode from "refractor/lang/peoplecode";
import perl from "refractor/lang/perl";
import php from "refractor/lang/php";
import phpdoc from "refractor/lang/phpdoc";
import php_extras from "refractor/lang/php-extras";
import plant_uml from "refractor/lang/plant-uml";
import plsql from "refractor/lang/plsql";
import powerquery from "refractor/lang/powerquery";
import powershell from "refractor/lang/powershell";
import processing from "refractor/lang/processing";
import prolog from "refractor/lang/prolog";
import promql from "refractor/lang/promql";
import properties from "refractor/lang/properties";
import protobuf from "refractor/lang/protobuf";
import pug from "refractor/lang/pug";
import puppet from "refractor/lang/puppet";
import pure from "refractor/lang/pure";
import purebasic from "refractor/lang/purebasic";
import purescript from "refractor/lang/purescript";
import python from "refractor/lang/python";
import qsharp from "refractor/lang/qsharp";
import q from "refractor/lang/q";
import qml from "refractor/lang/qml";
import qore from "refractor/lang/qore";
import r from "refractor/lang/r";
import racket from "refractor/lang/racket";
import cshtml from "refractor/lang/cshtml";
import jsx from "refractor/lang/jsx";
import tsx from "refractor/lang/tsx";
import reason from "refractor/lang/reason";
import regex from "refractor/lang/regex";
import rego from "refractor/lang/rego";
import renpy from "refractor/lang/renpy";
import rescript from "refractor/lang/rescript";
import rest from "refractor/lang/rest";
import rip from "refractor/lang/rip";
import roboconf from "refractor/lang/roboconf";
import robotframework from "refractor/lang/robotframework";
import ruby from "refractor/lang/ruby";
import rust from "refractor/lang/rust";
import sas from "refractor/lang/sas";
import sass from "refractor/lang/sass";
import scss from "refractor/lang/scss";
import scala from "refractor/lang/scala";
import scheme from "refractor/lang/scheme";
import shell_session from "refractor/lang/shell-session";
import smali from "refractor/lang/smali";
import smalltalk from "refractor/lang/smalltalk";
import smarty from "refractor/lang/smarty";
import sml from "refractor/lang/sml";
import solidity from "refractor/lang/solidity";
import solution_file from "refractor/lang/solution-file";
import soy from "refractor/lang/soy";
import sparql from "refractor/lang/sparql";
import splunk_spl from "refractor/lang/splunk-spl";
import sqf from "refractor/lang/sqf";
import sql from "refractor/lang/sql";
import squirrel from "refractor/lang/squirrel";
import stan from "refractor/lang/stan";
import stata from "refractor/lang/stata";
import iecst from "refractor/lang/iecst";
import stylus from "refractor/lang/stylus";
import supercollider from "refractor/lang/supercollider";
import swift from "refractor/lang/swift";
import systemd from "refractor/lang/systemd";
import t4_templating from "refractor/lang/t4-templating";
import t4_cs from "refractor/lang/t4-cs";
import t4_vb from "refractor/lang/t4-vb";
import tap from "refractor/lang/tap";
import tcl from "refractor/lang/tcl";
import tt2 from "refractor/lang/tt2";
import textile from "refractor/lang/textile";
import toml from "refractor/lang/toml";
import tremor from "refractor/lang/tremor";
import turtle from "refractor/lang/turtle";
import twig from "refractor/lang/twig";
import typescript from "refractor/lang/typescript";
import typoscript from "refractor/lang/typoscript";
import unrealscript from "refractor/lang/unrealscript";
import uorazor from "refractor/lang/uorazor";
import uri from "refractor/lang/uri";
import v from "refractor/lang/v";
import vala from "refractor/lang/vala";
import vbnet from "refractor/lang/vbnet";
import velocity from "refractor/lang/velocity";
import verilog from "refractor/lang/verilog";
import vhdl from "refractor/lang/vhdl";
import vim from "refractor/lang/vim";
import visual_basic from "refractor/lang/visual-basic";
import warpscript from "refractor/lang/warpscript";
import wasm from "refractor/lang/wasm";
import web_idl from "refractor/lang/web-idl";
import wgsl from "refractor/lang/wgsl";
import wiki from "refractor/lang/wiki";
import wolfram from "refractor/lang/wolfram";
import wren from "refractor/lang/wren";
import xeora from "refractor/lang/xeora";
import xml_doc from "refractor/lang/xml-doc";
import xojo from "refractor/lang/xojo";
import xquery from "refractor/lang/xquery";
import yaml from "refractor/lang/yaml";
import yang from "refractor/lang/yang";
import zig from "refractor/lang/zig";

export function registerAllLanguages() {
  registerLanguage(abap);
  registerLanguage(abnf);
  registerLanguage(actionscript);
  registerLanguage(ada);
  registerLanguage(agda);
  registerLanguage(al);
  registerLanguage(antlr4);
  registerLanguage(apacheconf);
  registerLanguage(apex);
  registerLanguage(apl);
  registerLanguage(applescript);
  registerLanguage(aql);
  registerLanguage(arduino);
  registerLanguage(arff);
  registerLanguage(armasm);
  registerLanguage(arturo);
  registerLanguage(asciidoc);
  registerLanguage(aspnet);
  registerLanguage(asm6502);
  registerLanguage(asmatmel);
  registerLanguage(autohotkey);
  registerLanguage(autoit);
  registerLanguage(avisynth);
  registerLanguage(avro_idl);
  registerLanguage(awk);
  registerLanguage(bash);
  registerLanguage(basic);
  registerLanguage(batch);
  registerLanguage(bbcode);
  registerLanguage(bbj);
  registerLanguage(bicep);
  registerLanguage(birb);
  registerLanguage(bison);
  registerLanguage(bnf);
  registerLanguage(bqn);
  registerLanguage(brainfuck);
  registerLanguage(brightscript);
  registerLanguage(bro);
  registerLanguage(bsl);
  registerLanguage(c);
  registerLanguage(csharp);
  registerLanguage(cpp);
  registerLanguage(cfscript);
  registerLanguage(chaiscript);
  registerLanguage(cil);
  registerLanguage(cilkc);
  registerLanguage(cilkcpp);
  registerLanguage(clojure);
  registerLanguage(cmake);
  registerLanguage(cobol);
  registerLanguage(coffeescript);
  registerLanguage(concurnas);
  registerLanguage(csp);
  registerLanguage(cooklang);
  registerLanguage(coq);
  registerLanguage(crystal);
  registerLanguage(css_extras);
  registerLanguage(csv);
  registerLanguage(cue);
  registerLanguage(cypher);
  registerLanguage(d);
  registerLanguage(dart);
  registerLanguage(dataweave);
  registerLanguage(dax);
  registerLanguage(dhall);
  registerLanguage(diff);
  registerLanguage(django);
  registerLanguage(dns_zone_file);
  registerLanguage(docker);
  registerLanguage(dot);
  registerLanguage(ebnf);
  registerLanguage(editorconfig);
  registerLanguage(eiffel);
  registerLanguage(ejs);
  registerLanguage(elixir);
  registerLanguage(elm);
  registerLanguage(etlua);
  registerLanguage(erb);
  registerLanguage(erlang);
  registerLanguage(excel_formula);
  registerLanguage(fsharp);
  registerLanguage(factor);
  registerLanguage(false_lang);
  registerLanguage(firestore_security_rules);
  registerLanguage(flow);
  registerLanguage(fortran);
  registerLanguage(ftl);
  registerLanguage(gml);
  registerLanguage(gap);
  registerLanguage(gcode);
  registerLanguage(gdscript);
  registerLanguage(gedcom);
  registerLanguage(gettext);
  registerLanguage(gherkin);
  registerLanguage(git);
  registerLanguage(glsl);
  registerLanguage(gn);
  registerLanguage(linker_script);
  registerLanguage(go);
  registerLanguage(go_module);
  registerLanguage(gradle);
  registerLanguage(graphql);
  registerLanguage(groovy);
  registerLanguage(haml);
  registerLanguage(handlebars);
  registerLanguage(haskell);
  registerLanguage(haxe);
  registerLanguage(hcl);
  registerLanguage(hlsl);
  registerLanguage(hoon);
  registerLanguage(http);
  registerLanguage(hpkp);
  registerLanguage(hsts);
  registerLanguage(ichigojam);
  registerLanguage(icon);
  registerLanguage(icu_message_format);
  registerLanguage(idris);
  registerLanguage(ignore);
  registerLanguage(inform7);
  registerLanguage(ini);
  registerLanguage(io);
  registerLanguage(j);
  registerLanguage(java);
  registerLanguage(javadoc);
  registerLanguage(javadoclike);
  registerLanguage(javastacktrace);
  registerLanguage(jexl);
  registerLanguage(jolie);
  registerLanguage(jq);
  registerLanguage(jsdoc);
  registerLanguage(js_extras);
  registerLanguage(json);
  registerLanguage(json5);
  registerLanguage(jsonp);
  registerLanguage(jsstacktrace);
  registerLanguage(js_templates);
  registerLanguage(julia);
  registerLanguage(keepalived);
  registerLanguage(keyman);
  registerLanguage(kotlin);
  registerLanguage(kumir);
  registerLanguage(kusto);
  registerLanguage(latex);
  registerLanguage(latte);
  registerLanguage(less);
  registerLanguage(lilypond);
  registerLanguage(liquid);
  registerLanguage(lisp);
  registerLanguage(livescript);
  registerLanguage(llvm);
  registerLanguage(log);
  registerLanguage(lolcode);
  registerLanguage(lua);
  registerLanguage(magma);
  registerLanguage(makefile);
  registerLanguage(markdown);
  registerLanguage(markup_templating);
  registerLanguage(mata);
  registerLanguage(matlab);
  registerLanguage(maxscript);
  registerLanguage(mel);
  registerLanguage(mermaid);
  registerLanguage(metafont);
  registerLanguage(mizar);
  registerLanguage(mongodb);
  registerLanguage(monkey);
  registerLanguage(moonscript);
  registerLanguage(n1ql);
  registerLanguage(n4js);
  registerLanguage(nand2tetris_hdl);
  registerLanguage(naniscript);
  registerLanguage(nasm);
  registerLanguage(neon);
  registerLanguage(nevod);
  registerLanguage(nginx);
  registerLanguage(nim);
  registerLanguage(nix);
  registerLanguage(nsis);
  registerLanguage(objectivec);
  registerLanguage(ocaml);
  registerLanguage(odin);
  registerLanguage(opencl);
  registerLanguage(openqasm);
  registerLanguage(oz);
  registerLanguage(parigp);
  registerLanguage(parser);
  registerLanguage(pascal);
  registerLanguage(pascaligo);
  registerLanguage(psl);
  registerLanguage(pcaxis);
  registerLanguage(peoplecode);
  registerLanguage(perl);
  registerLanguage(php);
  registerLanguage(phpdoc);
  registerLanguage(php_extras);
  registerLanguage(plant_uml);
  registerLanguage(plsql);
  registerLanguage(powerquery);
  registerLanguage(powershell);
  registerLanguage(processing);
  registerLanguage(prolog);
  registerLanguage(promql);
  registerLanguage(properties);
  registerLanguage(protobuf);
  registerLanguage(pug);
  registerLanguage(puppet);
  registerLanguage(pure);
  registerLanguage(purebasic);
  registerLanguage(purescript);
  registerLanguage(python);
  registerLanguage(qsharp);
  registerLanguage(q);
  registerLanguage(qml);
  registerLanguage(qore);
  registerLanguage(r);
  registerLanguage(racket);
  registerLanguage(cshtml);
  registerLanguage(jsx);
  registerLanguage(tsx);
  registerLanguage(reason);
  registerLanguage(regex);
  registerLanguage(rego);
  registerLanguage(renpy);
  registerLanguage(rescript);
  registerLanguage(rest);
  registerLanguage(rip);
  registerLanguage(roboconf);
  registerLanguage(robotframework);
  registerLanguage(ruby);
  registerLanguage(rust);
  registerLanguage(sas);
  registerLanguage(sass);
  registerLanguage(scss);
  registerLanguage(scala);
  registerLanguage(scheme);
  registerLanguage(shell_session);
  registerLanguage(smali);
  registerLanguage(smalltalk);
  registerLanguage(smarty);
  registerLanguage(sml);
  registerLanguage(solidity);
  registerLanguage(solution_file);
  registerLanguage(soy);
  registerLanguage(sparql);
  registerLanguage(splunk_spl);
  registerLanguage(sqf);
  registerLanguage(sql);
  registerLanguage(squirrel);
  registerLanguage(stan);
  registerLanguage(stata);
  registerLanguage(iecst);
  registerLanguage(stylus);
  registerLanguage(supercollider);
  registerLanguage(swift);
  registerLanguage(systemd);
  registerLanguage(t4_templating);
  registerLanguage(t4_cs);
  registerLanguage(t4_vb);
  registerLanguage(tap);
  registerLanguage(tcl);
  registerLanguage(tt2);
  registerLanguage(textile);
  registerLanguage(toml);
  registerLanguage(tremor);
  registerLanguage(turtle);
  registerLanguage(twig);
  registerLanguage(typescript);
  registerLanguage(typoscript);
  registerLanguage(unrealscript);
  registerLanguage(uorazor);
  registerLanguage(uri);
  registerLanguage(v);
  registerLanguage(vala);
  registerLanguage(vbnet);
  registerLanguage(velocity);
  registerLanguage(verilog);
  registerLanguage(vhdl);
  registerLanguage(vim);
  registerLanguage(visual_basic);
  registerLanguage(warpscript);
  registerLanguage(wasm);
  registerLanguage(web_idl);
  registerLanguage(wgsl);
  registerLanguage(wiki);
  registerLanguage(wolfram);
  registerLanguage(wren);
  registerLanguage(xeora);
  registerLanguage(xml_doc);
  registerLanguage(xojo);
  registerLanguage(xquery);
  registerLanguage(yaml);
  registerLanguage(yang);
  registerLanguage(zig);
}